### ISSUE TITLE
neo4j.exceptions.ClientError

### ISSUE THREAD

**Issue by whydee86** [fox-it/bloodhound-import#13]
Hi, I am trying to import the JSON file but, I am getting an exception:

```
Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-import", line 11, in <module>
  load_entry_point('bloodhound-import==0.0.4', 'console_scripts', 'bloodhound-import')()
  File "/usr/local/lib/python3.8/dist-packages/bloodhound_import-0.0.4-py3.8.egg/bloodhound_import/__init__.py", line 36, in main
  File "/usr/local/lib/python3.8/dist-packages/neo4j_driver-4.0.0a4-py3.8.egg/neo4j/work/simple.py", line 474, in write_transaction
  File "/usr/local/lib/python3.8/dist-packages/neo4j_driver-4.0.0a4-py3.8.egg/neo4j/work/simple.py", line 408, in _run_transaction
  File "/usr/local/lib/python3.8/dist-packages/neo4j_driver-4.0.0a4-py3.8.egg/neo4j/work/simple.py", line 580, in _close
  File "/usr/local/lib/python3.8/dist-packages/neo4j_driver-4.0.0a4-py3.8.egg/neo4j/work/simple.py", line 553, in sync
  File "/usr/local/lib/python3.8/dist-packages/neo4j_driver-4.0.0a4-py3.8.egg/neo4j/work/simple.py", line 267, in sync
  File "/usr/local/lib/python3.8/dist-packages/neo4j_driver-4.0.0a4-py3.8.egg/neo4j/io/_bolt3.py", line 379, in fetch_all
  File "/usr/local/lib/python3.8/dist-packages/neo4j_driver-4.0.0a4-py3.8.egg/neo4j/io/_bolt3.py", line 325, in fetch_message
  File "/usr/local/lib/python3.8/dist-packages/neo4j_driver-4.0.0a4-py3.8.egg/neo4j/io/_bolt3.py", line 511, in on_failure
  neo4j.exceptions.ClientError: There already exists an index :User(name). A constraint cannot be created until the index has been dropped.

```

**Comment by mwgielen** [comment]
Should be fixed on the bloodhound branch
