### ISSUE TITLE
bloodhound import fails on importing computers in ubuntu 20

### ISSUE THREAD

**Issue by 1nkotb** [fox-it/bloodhound-import#19]
**I have the following configuration**
ubuntu20
python 3

**I have installed the following** 
pip3
neo4j driver
running the latest bh 3.0.5
running the latest sharphound

When running  `bloodhound-import -du neo4j -dp "password" /my/path/*.json`, I am getting the following error

`[INFO] 2020-10-06 18:10:19,775 - Parsing 90 files

[INFO] 2020-10-06 18:10:19,775 - Parsing bloodhound file: /opt/import/20201005T0000019512/20201005000002_computers.json

Traceback (most recent call last):
  File "/usr/local/bin/bloodhound-import", line 8, in <module>
    sys.exit(main())

  File "/usr/local/lib/python3.8/dist-packages/bloodhound_import/__init__.py", line 44, in main
    parse_file(filename, driver)

  File "/usr/local/lib/python3.8/dist-packages/bloodhound_import/importer.py", line 437, in parse_file
    session.write_transaction(parse_function, entry)

  File "/home/user/.local/lib/python3.8/site-packages/neo4j/work/simple.py", line 403, in write_transaction
    return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)

  File "/home/user/.local/lib/python3.8/site-packages/neo4j/work/simple.py", line 309, in _run_transaction
    result = transaction_function(tx, *args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/bloodhound_import/importer.py", line 230, in parse_computer
    queries.append(Query(query, dict(source=entry['MemberId'], target=identifier)))

KeyError: 'MemberId'
`

**Comment by vruello** [comment]
This should be fixed by #20

**Comment by 1nkotb** [comment]
@vruello seems to be working now; thanks!
one more thing...I could open another issue if better...I am running sharphound for longer periods of time and it generates pretty big computer.json files which take hours to import...I was wondering if there is a way to trim the file for faster import?

**Comment by vruello** [comment]
@1nkotb I don't use sharphound, but as for as I know from Bloodhound.py, json files size is mostly determined by the size of your active directory domain (number of users, computers, groups...). You may reduce the size of computers.json if you use less collection methods, but I don't think that this will have a significant impact on performances, and you might miss important data.

An efficient way to improve insertion performances is to create indexes in neo4j. bloodhound-import uses only cypher requests looking like `MERGE (n:Base {objectid: ...}) ON MATCH ... ON CREATE ...`, which means that for each of these requests, neo4j needs to search for a node with label `Base` and the given `objectid`. Adding an index on `Base:objectid` improves considerably the speed of this operation. In my case, it reduced insertion duration from ~2 hours to less than 5 minutes.
The syntax is `CREATE INDEX FOR (n:Base) ON (n.objectid)`

**Comment by 1nkotb** [comment]
@vruello That is pretty fast...
I have tested in my environment and got 43 MB imported in 1:43 hours...
Not sure why I am getting such poor performance vs what you are getting...

**Comment by 1nkotb** [comment]
@vruello all good with speed now 👍 
thanks for your help!
one more thing I got into...since sharphound is now creating computer nodes at each loop, the scripts fails on adding newer files containing the same node... :(


Traceback (most recent call last):
  File "/home/import/.local/bin/bloodhound-import", line 8, in <module>
    sys.exit(main())
  File "/home/import/.local/lib/python3.8/site-packages/bloodhound_import/__init__.py", line 44, in main
    parse_file(filename, driver)
  File "/home/import/.local/lib/python3.8/site-packages/bloodhound_import/importer.py", line 437, in parse_file
    session.write_transaction(parse_function, entry)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/simple.py", line 403, in write_transaction
    return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/simple.py", line 309, in _run_transaction
    result = transaction_function(tx, *args, **kwargs)
  File "/home/import/.local/lib/python3.8/site-packages/bloodhound_import/importer.py", line 298, in parse_group
    tx.run(entry.query, props=entry.properties)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/transaction.py", line 118, in run
    result._tx_ready_run(query, parameters, **kwparameters)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 57, in _tx_ready_run
    self._run(query, parameters, None, None, None, **kwparameters)
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 101, in _run
    self._attach()
  File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 202, in _attach
    self._connection.fetch_message()
  File "/usr/local/lib/python3.8/dist-packages/neo4j/io/_bolt4.py", line 363, in fetch_message
    response.on_failure(summary_metadata or {})
  File "/usr/local/lib/python3.8/dist-packages/neo4j/io/_common.py", line 179, in on_failure
    raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.ConstraintError: {code: Neo.ClientError.Schema.ConstraintValidationFailed} {message: Node(17478) already exists with label                                                                                                  `Group` and property `name` = 'policy name@domain'}

**Comment by vruello** [comment]
@1nkotb 
> all good with speed now +1

Was adding the index enough? (I've seen your first reply and it was not as positive) Do you have some improvements statistics to share ? Maybe we should add this index by default when running bloodhound-import.

For your last error, the neo4j database can not contain two nodes labelled Group with the same name due to a unicity constraint enforced by bloodhound-import. To be honest, I am not sure to understand how you managed to get this to happen as nodes are merged with their Security Identifier.

**Comment by 1nkotb** [comment]
@vruello definitely the index helped 💯.
Instead if 4 hours or so, now I had 1:34 hours or so for a 60 MB file.
The issue was that my test machine was running on regular disk vs SDD. As soon as I run it on an SSD, it got somewhere around 2 minutes.
Is there a way in Neo4j to merge all characteristics of a group or node?
