### ISSUE TITLE
bloodhound import fails on importing new sharphound input

### ISSUE THREAD

**Issue by 1nkotb** [fox-it/bloodhound-import#22]
Sharphound with loop is creating multiple computers and users files and the script fails at importing new files

Traceback (most recent call last):
File "/home/import/.local/bin/bloodhound-import", line 8, in
sys.exit(main())
File "/home/import/.local/lib/python3.8/site-packages/bloodhound_import/init.py", line 44, in main
parse_file(filename, driver)
File "/home/import/.local/lib/python3.8/site-packages/bloodhound_import/importer.py", line 437, in parse_file
session.write_transaction(parse_function, entry)
File "/usr/local/lib/python3.8/dist-packages/neo4j/work/simple.py", line 403, in write_transaction
return self._run_transaction(WRITE_ACCESS, transaction_function, *args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/neo4j/work/simple.py", line 309, in _run_transaction
result = transaction_function(tx, *args, **kwargs)
File "/home/import/.local/lib/python3.8/site-packages/bloodhound_import/importer.py", line 298, in parse_group
tx.run(entry.query, props=entry.properties)
File "/usr/local/lib/python3.8/dist-packages/neo4j/work/transaction.py", line 118, in run
result._tx_ready_run(query, parameters, **kwparameters)
File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 57, in _tx_ready_run
self._run(query, parameters, None, None, None, **kwparameters)
File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 101, in _run
self._attach()
File "/usr/local/lib/python3.8/dist-packages/neo4j/work/result.py", line 202, in _attach
self._connection.fetch_message()
File "/usr/local/lib/python3.8/dist-packages/neo4j/io/_bolt4.py", line 363, in fetch_message
response.on_failure(summary_metadata or {})
File "/usr/local/lib/python3.8/dist-packages/neo4j/io/_common.py", line 179, in on_failure
raise Neo4jError.hydrate(**metadata)
neo4j.exceptions.ConstraintError: {code: Neo.ClientError.Schema.ConstraintValidationFailed} {message: Node(17478) already exists with label Group and property name = 'policy name@domain'}

**Comment by mwgielen** [comment]
I'll have to look into this deeper.
Strange that you get a contraint validation because it should be a MERGE insertion.

**Comment by 1nkotb** [comment]
> 
> 
> I'll have to look into this deeper.
> Strange that you get a contraint validation because it should be a MERGE insertion.

Hi @mwgielen!
Any chance for you to take a look at this?
Thanks!

**Comment by mwgielen** [comment]
Hi!
I haven't come across an error like this. Are you able to reproduce the error with the latest version?

**Comment by 1nkotb** [comment]
> 
> 
> Hi!
> I haven't come across an error like this. Are you able to reproduce the error with the latest version?

Hi!
I was using the latest version of bloodhound-import.
Now updating to BH 4.0.1 and will test it again; will come back with the results.

**Comment by 1nkotb** [comment]
> 
> 
> > Hi!
> > I haven't come across an error like this. Are you able to reproduce the error with the latest version?
> 
> Hi!
> I was using the latest version of bloodhound-import.
> Now updating to BH 4.0.1 and will test it again; will come back with the results.

This seems to be working now. Really curious what was causing the issues before...
