### ISSUE TITLE
import failes when importing *computers.json

### ISSUE THREAD

**Issue by 1nkotb** [fox-it/bloodhound-import#3]
`bloodhound-import -du "neo4j" -dp "password"  ~/Upload/1/20190206114521_computers.json`

please see the error message below:

[INFO] 2019-02-06 13:12:25,419 - Parsing 1 files
[INFO] 2019-02-06 13:12:25,420 - Parsing bloodhound file: /home/users/Upload/1/20190206114521_computers.json
Traceback (most recent call last):
  File "/home/user/.local/bin/bloodhound-import", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.5/site-packages/bloodhound_import/__init__.py", line 40, in main
    parse_file(filename, driver)
  File "/home/user/.local/lib/python3.5/site-packages/bloodhound_import/importer.py", line 402, in parse_file
    session.write_transaction(parse_function, entry)
  File "/home/user/.local/lib/python3.5/site-packages/neo4j/__init__.py", line 708, in write_transaction
    return self._run_transaction(WRITE_ACCESS, unit_of_work, *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/neo4j/__init__.py", line 674, in _run_transaction
    result = unit_of_work(tx, *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/bloodhound_import/importer.py", line 220, in parse_computer
    create_computer_query(tx, computer, query, 'DcomUsers', 'ExecuteDCOM')
  File "/home/user/.local/lib/python3.5/site-packages/bloodhound_import/importer.py", line 89, in create_computer_query
    for entry in computer[value]:
TypeError: 'NoneType' object is not iterable

**Comment by mwgielen** [comment]
I've implemented a fix for this problem, can you try it again with the dev branch?
(commit 2e798be5d3df4950f315e323c9d97e53036c5824)

**Comment by 1nkotb** [comment]
Thanks for changing it, but I am getting the same error. I even tried with a different computers.json file, but I got the same error.

**Comment by mwgielen** [comment]
Could you paste the traceback?

**Comment by 1nkotb** [comment]
there you go

[INFO] 2019-02-07 07:03:43,006 - Parsing 1 files
[INFO] 2019-02-07 07:03:43,007 - Parsing bloodhound file: /home/user/Upload/2                                                                                                                                                             0190130081740_computers.json
Traceback (most recent call last):
  File "/home/user/.local/bin/bloodhound-import", line 11, in <module>
    sys.exit(main())
  File "/home/user/.local/lib/python3.5/site-packages/bloodhound_import/__ini                                                                                                                                                             t__.py", line 40, in main
    parse_file(filename, driver)
  File "/home/user/.local/lib/python3.5/site-packages/bloodhound_import/impor                                                                                                                                                             ter.py", line 402, in parse_file
    session.write_transaction(parse_function, entry)
  File "/home/user/.local/lib/python3.5/site-packages/neo4j/__init__.py", lin                                                                                                                                                             e 708, in write_transaction
    return self._run_transaction(WRITE_ACCESS, unit_of_work, *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/neo4j/__init__.py", lin                                                                                                                                                             e 674, in _run_transaction
    result = unit_of_work(tx, *args, **kwargs)
  File "/home/user/.local/lib/python3.5/site-packages/bloodhound_import/impor                                                                                                                                                             ter.py", line 220, in parse_computer
    create_computer_query(tx, computer, query, 'DcomUsers', 'ExecuteDCOM')
  File "/home/user/.local/lib/python3.5/site-packages/bloodhound_import/impor                                                                                                                                                             ter.py", line 89, in create_computer_query
    for entry in computer.get(value, []):
TypeError: 'NoneType' object is not iterable

**Comment by mwgielen** [comment]
Thanks! I've committed another fix. Could you try again?
