### ISSUE TITLE
Two NoneType object is not iterable found

### ISSUE THREAD

**Issue by sbroosnokia** [fox-it/bloodhound-import#7]
When parsing the output of bloodhound I get two distinct 'NoneType' object is not iterable

(most recent call last):
  File "C:\Python27\Scripts\bloodhound-import-script.py", line 11, in <module>
    load_entry_point('bloodhound-import==0.0.2', 'console_scripts', 'bloodhound-import')()
  File "c:\python27\lib\site-packages\bloodhound_import\__init__.py", line 40, in main
    parse_file(filename, driver)
  File "c:\python27\lib\site-packages\bloodhound_import\importer.py", line 402, in parse_file
    session.write_transaction(parse_function, entry)
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 708, in write_transaction
    return self._run_transaction(WRITE_ACCESS, unit_of_work, *args, **kwargs)
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 674, in _run_transaction
    result = unit_of_work(tx, *args, **kwargs)
  File "c:\python27\lib\site-packages\bloodhound_import\importer.py", line 220, in parse_computer
    create_computer_query(tx, computer, query, 'DcomUsers', 'ExecuteDCOM')
  File "c:\python27\lib\site-packages\bloodhound_import\importer.py", line 89, in create_computer_query
    for entry in computer[value]:
TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "C:\Python27\Scripts\bloodhound-import-script.py", line 11, in <module>
    load_entry_point('bloodhound-import==0.0.2', 'console_scripts', 'bloodhound-import')()
  File "c:\python27\lib\site-packages\bloodhound_import\__init__.py", line 40, in main
    parse_file(filename, driver)
  File "c:\python27\lib\site-packages\bloodhound_import\importer.py", line 402, in parse_file
    session.write_transaction(parse_function, entry)
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 708, in write_transaction
    return self._run_transaction(WRITE_ACCESS, unit_of_work, *args, **kwargs)
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 674, in _run_transaction
    result = unit_of_work(tx, *args, **kwargs)
  File "c:\python27\lib\site-packages\bloodhound_import\importer.py", line 342, in parse_domain
    process_ace_list(tx, domain['Aces'], name, "Domain")
  File "c:\python27\lib\site-packages\bloodhound_import\importer.py", line 40, in process_ace_list
    for entry in ace_list:
TypeError: 'NoneType' object is not iterable

**Comment by mwgielen** [comment]
Hi, Could you try updating your installation?
It looks like a bug that should have be fixed in the latest version.

**Comment by sbroosnokia** [comment]
Yes, it is fixed in the latest version
