### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by sbroosnokia** [fox-it/bloodhound-import#9]
When uploading large json files (for example 500k groups), I sometimes get a "An existing connection was forcibly closed by the remote host". Please note that the database is running on localhost, so this is not due to connection problems.

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\bloodhound-import.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\bloodhound_import\__init__.py", line 40, in main
    parse_file(filename, driver)
  File "c:\python27\lib\site-packages\bloodhound_import\importer.py", line 408, in parse_file
    session.write_transaction(parse_function, entry)
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 363, in __exit__
    self.close()
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 396, in close
    self.rollback_transaction()
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 652, in rollback_transaction
    self._disconnect(sync=True)
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 380, in _disconnect
    self._connection.sync()
  File "c:\python27\lib\site-packages\neobolt\direct.py", line 505, in sync
    self.send()
  File "c:\python27\lib\site-packages\neobolt\direct.py", line 394, in send
    self._send()
  File "c:\python27\lib\site-packages\neobolt\direct.py", line 409, in _send
    self.socket.sendall(data)
  File "c:\python27\lib\ssl.py", line 759, in sendall
    v = self.send(data[count:])
  File "c:\python27\lib\ssl.py", line 725, in send
    v = self._sslobj.write(data)
socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host

Is it possible to add more robustness to the import?

**Comment by dirkjanm** [comment]
Some info I gathered from debugging this:
For very big objects the transaction becomes too large for the connection. The driver will push new things to the server but the server won't accept them anymore. This results in both the server and the client not doing anything until the server kills the connection after 15 minutes.
Maybe this is something they have to fix in the driver as well, though it doesn't seem to occur if we don't use transactions but run every query immediately.
Hope this helps @mwgielen :)

**Comment by sbroosnokia** [comment]
Any feedback about this issue? This is currently limiting the usability in automation, as the import of our largests datasets always fail

**Comment by mwgielen** [comment]
I haven't been able to look into this issue so far, however I'll try to come up with some solution the coming days.

**Comment by sbroosnokia** [comment]
Thanks alot for your support!

**Comment by mwgielen** [comment]
Could you try to use the dev branch (commit 5a057e3a40d35be0ff89ac944c5c0bb2d4c306fd) to import it? This commit changes the import method to auto commit .

**Comment by sbroosnokia** [comment]
I still seem to have the same issue

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\bloodhound-import.exe\__main__.py", line 9, in <module>
  File "c:\python27\lib\site-packages\bloodhound_import\__init__.py", line 40, in main
    parse_file(filename, driver)
  File "c:\python27\lib\site-packages\bloodhound_import\importer.py", line 406, in parse_file
    logging.debug("%s/%s", count, total)
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 363, in __exit__
    self.close()
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 401, in close
    self._disconnect(sync=True)
  File "c:\python27\lib\site-packages\neo4j\__init__.py", line 380, in _disconnect
    self._connection.sync()
  File "c:\python27\lib\site-packages\neobolt\direct.py", line 505, in sync
    self.send()
  File "c:\python27\lib\site-packages\neobolt\direct.py", line 394, in send
    self._send()
  File "c:\python27\lib\site-packages\neobolt\direct.py", line 409, in _send
    self.socket.sendall(data)
  File "c:\python27\lib\ssl.py", line 759, in sendall
    v = self.send(data[count:])
  File "c:\python27\lib\ssl.py", line 725, in send
    v = self._sslobj.write(data)
socket.error: [Errno 10054] An existing connection was forcibly closed by the remote host

**Comment by sbroosnokia** [comment]
After a couple of attempts, with this change the problem seems to occur even more frequently

**Comment by mwgielen** [comment]
I looked at the docs and the only thing that may help is the sync function.
https://neo4j.com/docs/api/python-driver/current/transactions.html#neo4j.neo4j.Session.Session.sync

Hopefully it will force to sync and wait for the server to ack.

**Comment by mwgielen** [comment]
Made an untested quick and dirty implementation of the comment above in commit f61b5c6ccd3d11aac9700571eb0cd87a4557ded9. I will test it later.

**Comment by sbroosnokia** [comment]
I am quite hopeful about these changes; I implemented the change already for the groups import and it is now running for two hours already without issues (before that raw data file stopped importing after 30 min with the error)

**Comment by sbroosnokia** [comment]
Ok, with the changes I succeeded importing a json file that I could never import before because of the issue

**Comment by mwgielen** [comment]
Closing this issue as it seems to be fixed.
